name: Risk_Asset_class_segmentation
description: |
  2.5 Business use case: Risk Asset class segmentation
version: '1.1'
author: nathan@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: riskassetclasssegmentation
  parentArtefactID: nathanprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-05-20 02:47:43'
pipelines:
  pipelines/Risk_Asset_Class_Segmentation:
    name: Risk_Asset_Class_Segmentation
    description: ''
    author: nathan@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-20 02:47:43'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-20 02:47:43'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules:
    businessRules/Risk_Asset_Class_Segmentation:
      name: Risk_Asset_Class_Segmentation
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nathan@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-05-21T00:37:04.441019Z'
  name: plibMaven
  version: 7.1.100
  id: '282555378'
  createdAt: '2024-05-21T00:37:04.440929Z'
- type: plibPypi
  modifiedAt: '2024-05-21T00:37:04.441074Z'
  name: plibPypi
  version: 1.8.23
  id: '1776187463'
  createdAt: '2024-05-21T00:37:04.44106Z'
projectDependencies:
  '225':
    projectUID: 225
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_225.git&subPath=
    version: 0.0.6.dev
    isDefault: true
    author: null
    createdAt: '2024-05-20 02:46:37'
  '224':
    projectUID: 224
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_224.git&subPath=
    version: 0.2.18.dev
    isDefault: true
    author: null
    createdAt: '2024-05-21 01:51:34'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
